-- local opts = {
-- 	nowait = true,
-- 	silent = true,
-- }
--
-- Keymap({ "n", "i" }, "<leader>su", '<esc>:execute "normal! i(<c-r>")"', opts)
--
-- Keymap("i", "<leader>spa", '<esc>:execute "normal! ciw(<c-r><c-w>)"<CR>A', opts)
-- Keymap("i", "<leader>sbr", '<esc>:execute "normal! ciw{<c-r><c-w>:}"<CR>i', opts)
